### PR TITLE
fix IE 11 development

### PR DESCRIPTION
**Pull request by thewillhuang**
## Summary

Rewrote the Object.defineProperty check in such a way so that IE11 will not fail as it currently still does.

## Test plan

Run tests through IE11, ensure current test suite does not fail

### CODE REVIEW

**Comment by kayhadrin** [comment]
Hi @thewillhuang,

Thanks for submitting a PR for this but I'm failing to see how the existing code is failing on IE11.
Which makes me unsure that your current PR is improving things.

Could you attach a detailed error report of what you're experiencing on IE11?

After reading the [IE8 section for the Object.defineProperty method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineproperty#Internet_Explorer_8_specific_notes) on the MDN, I think we should even add more steps to make sure it works as expected.

E.g.

```js
let canDefineProperty = false;
if (__DEV__) {
  try {
    Object.defineProperty({}, 'x', { // same settings as what we'll use during actual runtime
      configurable: false,
      enumerable: false,
      writable: false,
      value: 'foo',
    });
    canDefineProperty = true;
  } catch {
    // IE will fail on defineProperty
  }
}
```

**Comment by thewillhuang** [comment]
Sure thing, as you can see by going directly into IE's console, the current code results in a syntax error for IE11

### before

image

### after
image

this might be overtly on the safe side but It could handle even older browsers if we just guard for variables

**Comment by thewillhuang** [comment]
Hi, @kayhadrin I figured out the actual syntax error that was causing this IE11 bug to show up on development. I've modified the code to be as minimal change as well as the CR suggestions you added.

let me know what you think, thanks!

**Comment by thewillhuang** [comment]
Hey @kayhadrin, I've merged the fixed tests into this branch, looks like its good to go now

**Comment by kayhadrin** [comment]
Waiting for some GitHub permission issue to be resolve, and then I should be able to merge your PR.

**Comment by kayhadrin** [comment]
This issue will be fixed by eeda61f8bbe93c92ec0d839a244563863e7bf8b1.
I'll publish a new npm version of fbt soon.

**Comment by thewillhuang** [comment]
awesome! thanks a ton!

**Pull request closed without merging**
